#!/usr/bin/env bash

# Prompt user for input
read -p "What would you like to set the background opacity in kitty to ? " opacity

# Create the command with the entered opacity
command="kitty @ set-background-opacity -a $opacity"

# Execute the command
$command

# Display a confirmation message
echo "You have successfully set the background opacity in kitty to $opacity !"
